const express = require("express")
const router = express.Router()
const classController=require("../controller/classController")
router.get("/",classController.getClasses)
router.get("/schoolYear",classController.getClassesByYear)
//router.get("/:id", classController.getClasses)
router.post("/",classController.createNewClass)
router.delete("/",classController.deleteClass)
router.put("/",classController.updateClass)
module.exports = router