const express = require("express")
const verifyJWT = require("../middleware/verifyJWT")
const verifyAdmin = require("../middleware/verifyAdmin")
const router = express.Router()
const classController=require("../controller/classController")

router.use(verifyJWT)
router.use(verifyAdmin) 
router.get("/",classController.getClasses)
router.get("/schoolYear",classController.getClassesByYear)
router.get("/active",classController.getActiveClasses)
router.post("/",classController.createNewClass)
router.delete("/",classController.deleteClass)
router.put("/",classController.updateClass)
module.exports = router